### ISSUE TITLE
为什么无法成功PR

### ISSUE THREAD

**Issue by kangming06** [ByteLegendQuest/java-create-a-new-class#72]
![image](https://user-images.githubusercontent.com/74850890/139569827-6064ba1f-8561-43ab-b0cd-8eb83fb94f55.png)
![image](https://user-images.githubusercontent.com/74850890/139569852-e4a3c075-a181-4b7c-8142-6f7445b3831e.png)

**Comment by gtn1024** [comment]
See: [https://github.com/ByteLegend/ByteLegend/issues/83#issuecomment-955641600](https://github.com/ByteLegend/ByteLegend/issues/83#issuecomment-955641600)

**Comment by blindpirate** [comment]
1. 看清楚`src/main/java`和`src/test/java`。
2. GitHub默认不显示关闭的PR，需要点击“Closed”才能显示。你通过不了，是你的问题，现在有20多个PR通过了。

![image](https://user-images.githubusercontent.com/12689835/139571834-5dbae6f8-ecd7-4f22-9e9e-76d064b2f0f6.png)
